# Generated by Django 2.2 on 2021-04-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorited_by', models.ManyToManyField(related_name='favorited_products', to='Pop_App.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.CharField(max_length=255)),
                ('buyer_city', models.CharField(max_length=255)),
                ('buyer_state', models.CharField(max_length=255)),
                ('buyer_zip', models.IntegerField()),
                ('buyer_CC', models.IntegerField()),
                ('buyer_securtiy', models.IntegerField()),
                ('buyer_exp', models.DateField()),
                ('recipiant_name', models.CharField(max_length=255)),
                ('recipiant_address', models.CharField(max_length=255)),
                ('recipiant_city', models.CharField(max_length=255)),
                ('recipiant_state', models.CharField(max_length=255)),
                ('recipiant_zip', models.IntegerField()),
                ('ordered_products', models.ManyToManyField(related_name='included_in', to='Pop_App.Product')),
            ],
        ),
    ]
