# Generated by Django 3.1.7 on 2021-04-04 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pop_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='Pop_App.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_added', to='Pop_App.admin'),
            preserve_default=False,
        ),
    ]
